(define *g* (create-cfg))

;;;(define (foo)
;;;  10)
(let ((parent (define-global-func *g* 'foo))))

;;;(define (bar)
;;;  (foo))
(let ((parent (define-global-func *g* 'bar)))
	      (add-function-call *g* parent 'foo))

;;;(define (baz)
;;;  (define (foo)
;;;    12)
;;;  (foo))
(let ((parent (define-global-func *g* 'baz)))
  (define-sub-function *g* parent 'foo)
  (add-function-call *g* parent 'foo))

;;;(define (buzz)
;;;  (foo) ;; this causes error "premature reference" at define time
;;;  (define (foo)
;;;    12)
;;;  (foo))
(let ((parent (define-global-func *g* 'buzz)))
  (add-function-call *g* parent 'foo)
  (define-sub-function *g* parent 'foo)
  (add-function-call *g* parent 'foo))

;;;(define (fizz)
;;;  (define (foo)
;;;    (define (baz)
;;;      20)
;;;    (baz)
;;;    12)
;;;  (foo))
(let ((parent (define-global-func *g* 'fizz)))
  (let ((parent (define-sub-function *g* parent 'foo)))
    (define-sub-function *g* parent 'baz)
    (add-function-call *g* parent 'baz))
  (add-function-call *g* parent 'foo))
